# Copyright © 2025 Eser KUBALI <lxldev.contact@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of AURGen project and is licensed under
# the GNU General Public License v3.0 or later.
# See the LICENSE file in the project root for details.

name: ShellCheck

permissions:
  contents: read

on:
  push:
    paths:
      - 'bin/**'
      - 'dev-bin/**'
      - 'lib/**'
  pull_request:
    paths:
      - 'bin/**'
      - 'dev-bin/**'
      - 'lib/**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck on all shell files
        run: git ls-files '*.sh' 'bin/*' 'dev-bin/*' | xargs shellcheck 
