# Copyright © 2025 Eser KUBALI <lxldev.contact@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of AURGen project and is licensed under
# the GNU General Public License v3.0 or later.
# See the LICENSE file in the project root for details.

name: Functional Tests

permissions:
  contents: read

on:
  push:
    paths:
      - 'bin/**'
      - 'dev-bin/**'
      - 'lib/**'
  pull_request:
    paths:
      - 'bin/**'
      - 'dev-bin/**'
      - 'lib/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bash curl jq gnupg
      - name: Run basic tests (skip AURGen tests - requires Arch tools)
        run: |
          # Set up test environment
          export CI=1
          export RELEASE=0
          
          # Skip AURGen tests since they require Arch-specific tools (makepkg, updpkgsums)
          # that are not available on Ubuntu
          echo "Skipping AURGen functional tests - requires Arch Linux tools"
          echo "Tests can be run locally on Arch Linux with: ./bin/aurgen test" 