name: Functional Tests

permissions:
  contents: read

on:
  push:
    paths:
      - 'bin/**'
      - 'dev-bin/**'
      - 'lib/**'
  pull_request:
    paths:
      - 'bin/**'
      - 'dev-bin/**'
      - 'lib/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm bash util-linux base-devel pacman-contrib curl jq gnupg
      - name: Run aurgen functional tests
        run: |
          # Set up test environment
          export CI=1
          export RELEASE=0
          
          # Run the comprehensive test suite
          ./bin/aurgen test 